### PR TITLE
Added prune as supported, schedulable command

### LINKED ISSUE #22: Allow to schedule "prune"
This is a request to add `prune` to the list of `ScheduledSections`.

At the moment `check`, `backup` and `retention` can be scheduled. However one of the heaviest tasks, `prune` is not available. While retention can do `prune` as well it isn't very practical for large repositories (e.g. in my case, it runs +1 hour for a 500G repo on ordinary HDDs). 

While retention policies can differ per path and tag, `prune` should just be run once per-repo (and at a lower rate). A separate schedule option would allow to configure this easily.

### PR DESCRIPTION
**Pull request by jkellerer**
Fixes #22 

Implementation Notes:
* `profiles_test` & `show` was checked in with forced CRLF (other files were not). 
  The diff (without ignored whitespace) is larger than it should. Needs to be clarified if CRLF should be forced.
* I've consolidated schedule options since #23 may need one more schedulable section.
* All schedulable sections print with one newline in `show`. Needs to be clarified if this should be fixed.

~~Marked as WIP since I only tested it via `profiles_test` and on my mac so far.~~

Tested in regular backup schedule and via unit and manual tests.

### CODE REVIEW

**Comment by jkellerer** [comment]
Self note: `resticprofile show` returns invalid content with this change. Needs to be checked.

**Comment by jkellerer** [comment]
Please note that the fix for `show` adds one newline. I‘d fix this before merge, however would like to get feedback first.

**Comment by creativeprojects** [comment]
Sure, I have been a bit busy, sorry about that.
I'll have a look at it in the next few days 👍🏻 

Thanks

**Comment by creativeprojects** [comment]
I see the two annoying files with CRLF ending, it's because sometimes I fix things on my work laptop.
To make things easier I can change them to LF and then maybe we can rebase the PR?

Sorry about that

**Comment by jkellerer** [comment]
Yes sure, that would be great.

**Comment by creativeprojects** [comment]
Can you try a rebase now?

**Comment by creativeprojects** [comment]
Cool, thanks

I like the way you refactored the scheduling config into `ScheduleSection`, nice one 👍🏻 

I understand now why you had to change the code of the `show` command, I have to admit I was a bit puzzled over the holidays when I glanced at the PR message 😆 

I'm looking at the newline issue; I realise the code of the `show` command is rather messy. I remember I was learning go reflection on this one...

**Comment by creativeprojects** [comment]
It's ok for the `show` command, I need to work on it later.

Thanks fo the PR 👍🏻

**Comment by jkellerer** [comment]
Thanks a lot for reviewing and merging!

**Pull request merged**
