### PR TITLE
Build option to disable self update

### LINKED ISSUE #170: Please provide a build time option to disable self-update
for packagers it would be helpful if we could turn off the self update. restic itself solves that via a [tag](https://github.com/restic/restic/blob/master/build.go#L59). maybe a similar solution could be applied here?

### PR DESCRIPTION
**Pull request by creativeprojects**
This is mostly moving code around, except:
- creation of a `OwnCommands` struct so we can register and keep a list of commands
- pass `ownCommands` slice to `Completer` to avoid using a global reference directly (doesn't make a big difference but is more future proof)
- add a `no_self_update` tag to build resticprofile without the self updater

Fixes #170

### CODE REVIEW

**Comment by jkellerer** [comment]
Thanks for requesting a review 😀

Using a custom type for managing the own commands list is in general a good idea!

Only thing I'm not yet sure of is if the help commands fully fits inside of it since it is not only about own commands. Also some changes had been made in "https://github.com/creativeprojects/resticprofile/pull/178/files", e.g. `runOwnCommand` no longer calls `displayHelpCommand` so it is no longer tangled together which I didn't like so much in the first place.

From my opinion, it would be better to keep the help command separate (just like any other command) and only include implementations that relate to command list management (some of the display code may be included though).

**Comment by creativeprojects** [comment]
> Only thing I'm not yet sure of is if the help commands fully fits inside of it since it is not only about own commands. Also some changes had been made in "https://github.com/creativeprojects/resticprofile/pull/178/files", e.g. `runOwnCommand` no longer calls `displayHelpCommand` so it is no longer tangled together which I didn't like so much in the first place.

No problem, I'll wait until you're happy to merge #178 

> From my opinion, it would be better to keep the help command separate (just like any other command) and only include implementations that relate to command list management (some of the display code may be included though).

I totally agree with that: But I've done it like that because we would need to change the signature of the run function to include a reference to the OwnCommands instance. I suppose it kind of make sense but we will only use the reference in the help command.

**Comment by jkellerer** [comment]
Have just merged the PR.

Ah yes, I overlooked that we need this reference. How about changing the signature of `Run` to include a context type. It then is easier to adjust things as the context type can be changed instead?

**Comment by jkellerer** [comment]
What I mean is, change the command func signature to something like `func(io.Writer, CommandRequest) error`

**Comment by creativeprojects** [comment]
Yeah I might as well 👍🏻

**Comment by creativeprojects** [comment]
It certainly looks better 😉

**Review by jkellerer — APPROVED** [review]
lgtm!

**Pull request merged**
