### PR TITLE
Schedule: Capture `os.Environ` on schedule creation

### PR DESCRIPTION
**Pull request by jkellerer**
Fixes: #211 

The PR adds a new config option `schedule-capture-environment` defaulting to `RESTIC_*` which enables OS environment capturing for schedules at creation time.

@creativeprojects - what do you think (it is an enhancement to the existing capture of the profile env)? 
Does this work with #146 ?

### CODE REVIEW

**Comment by jkellerer** [comment]
@creativeprojects , btw. not all platforms have case insensitive variables. But this PR makes env vars case insensitive in all cases. Should we differentiate it by platform? 

(I think yes we should)

**Comment by creativeprojects** [comment]
> what do you think (it is an enhancement to the existing capture of the profile env)? Does this work with #146 ?

I don't think it would clash with #146 so we're good 👍🏻 

> not all platforms have case insensitive variables. But this PR makes env vars case insensitive in all cases. Should we differentiate it by platform?

Yeah probably 😐  I'm not too familiar with powershell but I'm pretty sure that could cause some issues.

**Comment by jkellerer** [comment]
Env vars will now preserve the case. Case folding only applies on Windows. Will manually test the changes first.

**Comment by jkellerer** [comment]
Works fine in launchd. Systemd test is pending

**Comment by jkellerer** [comment]
Think it can be merged. @creativeprojects , what do you think? 

Please check the environment variables part. I think it works correct now, given the limitation that the config doesn't allow to specify the case, but all unix OS are case sensitive for env vars. 

The implementation was adjusted to this:
* If the config defines a variable that exists in the environment, the config value overrides the existing var when the name matches. Case is not considered, there is a resolve step for this that adjusted the name.
* If the config defines a new variable, it will be all upper-cased like it was before.

**Review by creativeprojects — APPROVED** [review]
Yes it works well, nice one!

I think we're good to go with this one as well 👍🏻 

Thank you for the great work 😉

**Pull request merged**
