### PR TITLE
restic: use repository-file if the repo flag contains a password

### PR DESCRIPTION
**Pull request by jkellerer**
Experimental PR to replace `restic --repo https://user:password@host` with `restic --repository-file /tmp/profile-repo.txt` (with file mode `0600`)

Currently fails tests (as they don't expect replacement) and depends on some functions from other PRs to complete it.

### CODE REVIEW

**Comment by creativeprojects** [comment]
I guess this is to hide the password if someone looks at the process list?

Makes sense 👍🏻

**Comment by jkellerer** [comment]
Exactly. A process list may also be sent by monitoring software so its easy to leak passwords around.

**Comment by jkellerer** [comment]
Tests are fixed and the enhancement disables itself when it detects that the repo is set by env variables

**Review by creativeprojects — APPROVED** [review]
I tried it on one of my REST repo and it worked like a charm 🥇 

Nice one! thanks 😉

**Pull request merged**
