### PR TITLE
schedule: added unified schedule config struct

### PR DESCRIPTION
**Pull request by jkellerer**
Draft for schedule structs discussed in #80 

```yaml
# defaults in global section
global:
  systemd-drop-in-files:
    - "default-drop-in.conf"

  schedule-defaults:
    log: /path/to/default-schedule.log
    lock-wait: 60m

# inline or schedule structure type config in profile command sections
default:
  systemd-drop-in-files:
    - "profile-operrides.conf"

  # inline
  check:
    schedule:
      - weekly
    schedule-log: /path/to/check.log

  # schedule structure
  backup:
    schedule:
      at: "daily"
      log: /path/to/backup-schedule.log
      lock-wait: 30m
```

.. and finally group support (in this PR, it is config only. Also needs updates to scheduling (partially done in #290), coming later):

```yaml
version = 2

groups:
  all:
    profiles: "*"
    schedules:
      backup:
        at: "daily"
        log: /path/to/backup-schedule.log
        lock-wait: 30m
```

### CODE REVIEW

**Comment by jkellerer** [comment]
@creativeprojects , think it is ready now. had it running on one of my machines and schedules work like before (had them recreated to use run-schedule).

**Comment by creativeprojects** [comment]
I looked at the MR and so far it all looks good to me.
I'm going to play with it on some of my configs and see how it goes 👍🏻

**Comment by jkellerer** [comment]
Thanks for checking!

**Review by creativeprojects — APPROVED** [review]
It works fine 😛 

Thank you for the great work 😉 

I think we can merge it and I'll install it on more instances for good measure

**Comment by jkellerer** [comment]
Had already began refactoring #290 to allow scheduling groups. That is the only remaining part.

**Pull request merged**
