### PR TITLE
Add contributed docs for protected configuration on Windows

### PR DESCRIPTION
**Pull request by danielfdickinson**
Details creating resticprofile and resticlogs folders for protected profiles configuration and logs for system-level resticprofile.

### CODE REVIEW

**Comment by danielfdickinson** [comment]
@coderabbitai review

**Comment by danielfdickinson** [comment]
@creativeprojects, do you want me to push just the contrib README (no edit to the contributions page) and push the contributions page separately, or do you wish to handle this?

**Comment by creativeprojects** [comment]
Do you mean separating into 2 PR to fix the build?
If that's the case don't worry about it, the documentation will be built after merging.

**Comment by creativeprojects** [comment]
I tried it on my Windows VM and it works fine 👍🏻 
I'll merge it if you're happy with it

Thanks for the contribution 🍾 🥳

**Comment by danielfdickinson** [comment]
Yes, I meant separating the two PRs. Thank you for testing, and I am happy with it and look forward to seeing it merged. I'm glad you find it helpful and that I could contribute.

Cheers!

**Pull request merged**
