### PR TITLE
Retention: Align host filter with "backup"

### PR DESCRIPTION
**Pull request by jkellerer**
Aligns the `--host` filter of "retention" (forget) with "backup" in restic (if host is not set, it defaults to [`os.Hostname()`](https://github.com/restic/restic/blob/237f32c651d4924242783a02c9a52b09ccc2dc4f/cmd/restic/cmd_backup.go#L48) in restic, but forget has no default matching all hosts if unset)

After this change, when using `retention` in version 2 configs, all 3 filters `path`, `tags` and `host` are aligned with the `backup` section if not redefined.

Other changes:
* Auto enables `after-backup: true` if nothing was specified explicitly but `keep-*` is set
  (to avoid case like #226).
* Fixes a problem with the `tag` copy from `backup`. Tags must be copied as single flag (`"tag1,tag2,tag3,..."`) instead of multiple flags to match correctly
  (mentioned in #225)

@creativeprojects : before I create tests, what do you think on this?

### CODE REVIEW

**Comment by creativeprojects** [comment]
>  before I create tests, what do you think on this?

Yes this is a good idea 👍🏻 

I was also thinking we should fix the inconsistency of `retention.after-backup` and `backup.check-after` but that's out of the scope of this MR.

Sorry I'm very busy this week, and the next one as well. We're deploying a new project to production next week 😉

**Comment by jkellerer** [comment]
@creativeprojects , think the PR is ready for review now. What do you think?

**Review by creativeprojects — APPROVED** [review]
LGTM 😄 

BTW we should keep track of all the subtle differences between v1 and v2 so we can make a exhaustive upgrade documentation

Thanks 😉

**Comment by jkellerer** [comment]
Guess we’ll need to review usages of `config.Version` when we document differences. This time it is in the reference at least 🙂

**Pull request merged**
