### PR TITLE
Add support for scheduling forget

### PR DESCRIPTION
**Pull request by jkellerer**
As discussed in #23 , this adds support for scheduling forget.

### CODE REVIEW

**Comment by jkellerer** [comment]
Let me know, if tests are required for the 2 refactored lines

**Comment by creativeprojects** [comment]
> Let me know, if tests are required for the 2 refactored lines

I wouldn't say required, but if they are easy to test, that would be a nice to have.

Otherwise that looks good to me 👍🏻

**Comment by jkellerer** [comment]
Well, I guess if code analysis already tells us that we shouldn't be lazy, we should listen to it :)

I've kept the original test and leave it up to you if both tests should remain. The original test still has some extra value since it covers 2 conditions (true and actual value) in a single invocation.

**Comment by jkellerer** [comment]
Not entirely certain what caused the test aborts. Tests run fine locally (besides TestUpdate which was very slow today, but is skipped here).

**Comment by creativeprojects** [comment]
> Not entirely certain what caused the test aborts. Tests run fine locally (besides TestUpdate which was very slow today, but is skipped here).

I have a flaky test since I moved from Travis CI to GitHub Actions. Not sure what's happening, it aways works fine locally (TestInterruptShellCommand)

**Comment by creativeprojects** [comment]
Nice work. I'll gradually update my backup configurations as I have a few using `retention` and I'll display a deprecation warning.

Thanks

**Pull request merged**
