### PR TITLE
env-file: Implement dotenv and {{env}} support

### PR DESCRIPTION
**Pull request by jkellerer**
Implementation of #316

Supporting:

* `env-file` in profiles:

   ```yaml
     my-profile:
       env-file: /path/to/.env
   ```

* `{{env}}` function to get a temporary .env file that can be used to adjust the environment between shell command runs:

   ```yaml
     my-profile:
       run-before: echo "VAR=WORLD" >> "{{env}}"
       backup:
         run-before: echo "Hello $VAR"
   ```

### CODE REVIEW

**Comment by creativeprojects** [comment]
I can see there are still some broken links in the documentation since the latest version of Hugo 😞 
Maybe I should just pin the version for now 🤔 that's annoying

**Review by creativeprojects — COMMENTED** [review]
GitHub doesn't seem to let me add comments on lines that haven't been changed, or am I going mad? 🤔  

Anyway... in the functions `runShellCommands` and `runFinalShellCommands` we create the environment only once for the list of commands. So if we declare a variable in the first command, we wouldn't have it available in the second one (and so forth).

I suppose it could be useful in case we want to do something like:

```yaml
run-before:
  - "echo \"USER=GUEST\" >> {{ env }}"
  - "echo \"HOME=/home/$USER\" >> {{ env }}"
```

...which is actually a terrible example because `godotenv` library would take care of it for us 🤣 

Do we need to restore the environment on each line?

**Comment by jkellerer** [comment]
Rebased and updated so that env is created for every shell command invocation. Done from my side.

**Review by creativeprojects — APPROVED** [review]
LGTM.
Tried on my side and it works all fine 👍🏻 

Although I was thinking about moving the "setting up environment variables" debug to trace level instead as it's becoming quite verbose 🤔

**Comment by jkellerer** [comment]
Agree that it all became too verbose with the `--verbose` flag enabled. Still I think changes to the env is an important log output. I've reduced unfiltered-log to trace level and changed the env log to display the full env only when it was changed.

E.g. it now looks like this:

```
/resticprofile --verbose containers.backup
2024/03/10 14:09:29 resticprofile 0.27.0-dev
2024/03/10 14:09:29 using configuration file: /etc/resticprofile/profiles.yaml
...
2024/03/10 14:09:29 profile 'containers': initializing repository (if not existing)
2024/03/10 14:09:29 command environment:
TMPDIR=/tmp

2024/03/10 14:09:29 starting command: /usr/bin/restic init ...
2024/03/10 14:09:29 starting run-before backup on profile 1/1
2024/03/10 14:09:29 command environment: reusing previous
Create a readonly snapshot of '/opt/containers' in '/opt/snapshot_containers'
2024/03/10 14:09:29 profile 'containers': starting 'backup'
2024/03/10 14:09:29 command environment: reusing previous
2024/03/10 14:09:29 starting command: /usr/bin/restic backup ... /opt/snapshot_containers
```

**Comment by creativeprojects** [comment]
> Agree that it all became too verbose with the `--verbose` flag enabled. Still I think changes to the env is an important log output. I've reduced unfiltered-log to trace level and changed the env log to display the full env only when it was changed.

Perfect!
Thanks 😉

**Pull request merged**
