### PR TITLE
Enhanced "unschedule" to remove all possible jobs

### PR DESCRIPTION
**Pull request by jkellerer**
This change ensures that schedules that are no longer defined in the config will still attempted to be removed from the os scheduler. It addresses one part of #27 to remove all schedules for one profile.

Notes:
* ~~Currently this is a first draft without any testing as basis for discussing the general direction.~~
* The implementation tries to be as generic as possible to support all os schedulers.
* There is no dependency on OS schedulers to list registered jobs and as a consequence, renamed profiles may still leave scheduled jobs behind. A fix for this may be added in a separate PR.

### CODE REVIEW

**Comment by creativeprojects** [comment]
> * The files `schedule_unix` and `schedule_windows` have the CRLF issue which increases the diff if whitespace is not ignored. Let me know when this is fixed and I'll rebase.

Argl. Sorry, I've fixed them, you can rebase 😊

**Comment by jkellerer** [comment]
Rebase is done

**Comment by creativeprojects** [comment]
Thanks.

So it doesn't need a schedule configuration to be able to unschedule it: only a profile name and that's all fine in this case.

Now, thinking a bit further, for `unschedule --all`, we would miss it if we changed the named of a profile.
I reckon it's not something very common but I do remember changing profile names in the past when moving backup between servers.
So we need to be able to handle that case as well. Worst case scenario we could keep a state file.

**Comment by jkellerer** [comment]
Good point. I could imagine for os schedulers that support it, they could return a list of profile names which are then added in addition to known profile names for the `--all` option. That way we might still use the `systemctl list` command to get this list, but if for any reason the list cannot be generated it still works on all names that are known by the configuration.

**Comment by creativeprojects** [comment]
For launchd it's a matter of reading a couple of directories and check the file names from the pattern
For Task Scheduler on Windows it's a matter of loading a list of tasks and check their names as well.

Definitely doable 👍🏻

**Comment by jkellerer** [comment]
Sounds like a plan 👍 . So I'll finish this PR with unit tests unless you have some other concerns?

**Comment by creativeprojects** [comment]
> Sounds like a plan 👍 . So I'll finish this PR with unit tests unless you have some other concerns?

I think that should work, no other concern I can think of

**Comment by creativeprojects** [comment]
By the way @jkellerer , the schedule package was getting a bit messy so I'm doing some refactoring what will easily fix this issue.

There will be two objects:
- a Schedule object with methods on a profile
- a Job object like before

All of these accessible through interfaces as well. That's making things more extensible 👍🏻

**Comment by jkellerer** [comment]
@creativeprojects , thanks a lot for the note. Haven't had time yet to continue but I'll wait for your commit first so avoid any double effort.

**Comment by jkellerer** [comment]
Unit tests have been added and I've also verified it manually on MacOS & Linux. Removed WIP flag.

**Comment by creativeprojects** [comment]
Cool 👍🏻 
I'll try it out some time this week
Thanks

**Comment by creativeprojects** [comment]
Yep, looks good to me, thanks again 😄

**Comment by jkellerer** [comment]
Thanks as well!

**Pull request merged**
